### ISSUE TITLE
Pledge page isn't responsive. Looks cluttered on mobile.

### ISSUE THREAD

**Issue by sanspace** [pullrequestday/pullrequestday#28]
![screenshot_2015-11-09-09-05-42](https://cloud.githubusercontent.com/assets/347714/11026614/b071b39e-86d2-11e5-8e8e-d38098fc4810.png)

This is on Nexus 4 Chrome.

**Comment by davidmiller** [comment]
This has been solved by the super @andylolz in #31 ! :)

**Comment by andylolz** [comment]
Getting a headstart on pull request day :)
