### ISSUE TITLE
GitHub and Twitter links in the pledges - Should we normalize them?

### ISSUE THREAD

**Issue by augustoproiete** [pullrequestday/pullrequestday#43]
Ultra-minor issue and yes... Very pedantic, I know :).

I'm thinking if we shouldn't remove all the "@" symbols in front of the links to people's twitter and GitHub profiles, given we already show the icon.

Or maybe, leave the "@" for Twitter links, and not have the "@" for GitHub links?

The message on the site says that we should include the "@" in both links, but I kind of like what Camille and Mike did here:

![image](https://cloud.githubusercontent.com/assets/177608/11170145/7aa36774-8ba2-11e5-8cdf-e35d377e473b.png)

**Comment by M-Zuber** [comment]
I vote for removing the @ from Github links as it is not used so much. Twitter on the other hand has @ as more of an integral part of the user name.
